### ISSUE TITLE
Verify WL values

### ISSUE THREAD

**Issue by joaoftrodrigues** [joaoftrodrigues/atpdb-cleanup-and-conversion-to-relational#11]
# Description

_WL_ informs if the respective player won or lost, on a tournament phase. It was found that there was other values then W or L, so the possible values must be check, to do a cleaning process if needed.

# Steps

1. Check values that are not W or L
2. Establish if there's a need to clean
3. Clean if needed was established.

**Comment by inescelorico** [comment]
db.atpplayers.updateMany({"WL":""},{$set:{"WL":null}})
